espipe:
  elasticsearch:
    host: localhost
    port: 9200
    protocol: http
    # fields_mode: flatten, custom_in_one[default], all_in_one[not support yet]
    fields_mode: custom_in_one
    bulk_size: 12000

spring:
  # improve fetch data from database performance
  # datasource.hikari.auto-commit: false
  # save 50% of performance by set fetch-size to 100, default is 10, 100k is reduced 7s to 3.5s
  jdbc.template.fetch-size: 100
  task.scheduling.pool.size: 4
